# Generated by Django 5.0.3 on 2026-01-20 19:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('explicit', 'Explicit'), ('inferred', 'Inferred'), ('restriction', 'Restriction')], default='explicit', max_length=20)),
                ('category', models.CharField(help_text="Preference category (e.g., 'dietary', 'flavor', 'packaging')", max_length=50)),
                ('key', models.CharField(help_text="Preference name (e.g., 'lactose_free', 'favorite_bread')", max_length=100)),
                ('value', models.JSONField(default=dict, help_text='Preference value (can be bool, string, list, etc.)')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='0.00 to 1.00 - confidence in inferred preference', max_digits=3)),
                ('source', models.CharField(blank=True, help_text="Preference source (e.g., 'order:123', 'form', 'chat')", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='guestman.customer')),
            ],
            options={
                'verbose_name': 'Preference',
                'verbose_name_plural': 'Preferences',
                'ordering': ['category', 'key'],
                'unique_together': {('customer', 'category', 'key')},
            },
        ),
    ]
