# Generated by Django 5.2.11 on 2026-02-21 16:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0005_alter_processedevent_options_and_more'),
        ('guestman_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpreference',
            options={'ordering': ['category', 'key'], 'verbose_name': 'preferência', 'verbose_name_plural': 'preferências'},
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='category',
            field=models.CharField(help_text="Categoria da preferência (ex: 'dietética', 'sabor', 'embalagem')", max_length=50, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='0.00 a 1.00 - confiança na preferência inferida', max_digits=3, verbose_name='confiança'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='guestman.customer', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='key',
            field=models.CharField(help_text="Nome da preferência (ex: 'sem_lactose', 'pao_favorito')", max_length=100, verbose_name='chave'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='preference_type',
            field=models.CharField(choices=[('explicit', 'Explícita'), ('inferred', 'Inferida'), ('restriction', 'Restrição')], default='explicit', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='source',
            field=models.CharField(blank=True, help_text="Origem da preferência (ex: 'pedido:123', 'formulário', 'chat')", max_length=100, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='customerpreference',
            name='value',
            field=models.JSONField(default=dict, help_text='Valor da preferência (pode ser bool, string, lista, etc.)', verbose_name='valor'),
        ),
    ]
