# Generated by Django 5.0.3 on 2026-01-20 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique customer code (e.g., CUST-001)', max_length=50, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20)),
                ('document', models.CharField(blank=True, db_index=True, help_text='CPF or CNPJ (numbers only)', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('source_system', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_list_code', models.CharField(blank=True, help_text='Price list code in Offerman (convention: slug=code)', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Default group for new customers')),
                ('priority', models.IntegerField(default=0, help_text='Higher = more priority')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('label_custom', models.CharField(blank=True, help_text='Custom label when label=other', max_length=50)),
                ('place_id', models.CharField(blank=True, help_text='Google Places ID', max_length=255)),
                ('formatted_address', models.CharField(help_text='Complete formatted address', max_length=500)),
                ('street_number', models.CharField(blank=True, max_length=20)),
                ('route', models.CharField(blank=True, help_text='Street name', max_length=200)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('state_code', models.CharField(blank=True, help_text='State code', max_length=5)),
                ('postal_code', models.CharField(blank=True, help_text='ZIP code', max_length=20)),
                ('country', models.CharField(default='Brasil', max_length=100)),
                ('country_code', models.CharField(default='BR', max_length=5)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('complement', models.CharField(blank=True, help_text='Apt, building, reference', max_length=100)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Instructions for delivery')),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Address verified via Google Places')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='guestman.customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', 'label'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='guestman.customergroup'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='guestman_cu_code_110a56_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['document'], name='guestman_cu_documen_5865dc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='guestman_cu_phone_5795fb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='guestman_cu_email_3d18f8_idx'),
        ),
    ]
