# Generated by Django 5.0.3 on 2026-01-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0002_contactpoint_externalidentity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactpoint',
            new_name='guestman_co_custome_4e8796_idx',
            old_name='guestman_co_custome_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='contactpoint',
            new_name='guestman_co_type_3cacdf_idx',
            old_name='guestman_co_type_va_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='externalidentity',
            new_name='guestman_ex_custome_3eb7e8_idx',
            old_name='guestman_ex_custome_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='externalidentity',
            new_name='guestman_ex_provide_6f5b5f_idx',
            old_name='guestman_ex_provide_j0k1l2_idx',
        ),
    ]
