# Generated by Django 5.2.10 on 2026-01-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0003_rename_guestman_co_custome_a1b2c3_idx_guestman_co_custome_4e8796_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpoint',
            options={'ordering': ['-is_primary', '-created_at'], 'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-is_default', 'label'], 'verbose_name': 'endereço', 'verbose_name_plural': 'endereços'},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'grupo de clientes', 'verbose_name_plural': 'grupos de clientes'},
        ),
        migrations.AlterModelOptions(
            name='externalidentity',
            options={'ordering': ['-created_at'], 'verbose_name': 'identidade externa', 'verbose_name_plural': 'identidades externas'},
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='guestman.customer', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='principal'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verificado'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Telefone (voz/SMS)'), ('email', 'Email'), ('instagram', 'Instagram')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='value_display',
            field=models.CharField(blank=True, help_text='Formato amigável para exibição.', max_length=255, verbose_name='valor para exibição'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='value_normalized',
            field=models.CharField(db_index=True, help_text='Telefone em E.164 (+5541999998888) ou email em minúsculas.', max_length=255, verbose_name='valor normalizado'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='verification_method',
            field=models.CharField(choices=[('unverified', 'Não verificado'), ('channel_asserted', 'Verificado pelo canal'), ('otp_whatsapp', 'OTP via WhatsApp'), ('otp_sms', 'OTP via SMS'), ('email_link', 'Link por email'), ('manual', 'Manual (equipe)')], default='unverified', max_length=20, verbose_name='método de verificação'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='verification_ref',
            field=models.CharField(blank=True, help_text='Referência externa (ex: Manychat subscriber_id).', max_length=255, verbose_name='referência de verificação'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verificado em'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(help_text='Código único do cliente (ex: CLI-001)', max_length=50, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Pessoa Física'), ('business', 'Pessoa Jurídica')], default='individual', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.CharField(blank=True, db_index=True, help_text='CPF ou CNPJ (apenas números)', max_length=20, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email (legado)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='guestman.customergroup', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefone (legado)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='sistema de origem'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='complement',
            field=models.CharField(blank=True, help_text='Apto, bloco, referência', max_length=100, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='Brasil', max_length=100, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country_code',
            field=models.CharField(default='BR', max_length=5, verbose_name='código do país'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='guestman.customer', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Instruções para o entregador', verbose_name='instruções de entrega'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='formatted_address',
            field=models.CharField(help_text='Endereço completo formatado', max_length=500, verbose_name='endereço formatado'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='padrão'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Endereço verificado via Google Places', verbose_name='verificado'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(choices=[('home', 'Casa'), ('work', 'Trabalho'), ('other', 'Outro')], default='home', max_length=20, verbose_name='rótulo'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label_custom',
            field=models.CharField(blank=True, help_text='Rótulo personalizado quando tipo=outro', max_length=50, verbose_name='rótulo personalizado'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='place_id',
            field=models.CharField(blank=True, help_text='ID do Google Places', max_length=255, verbose_name='ID do Google Places'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Código postal', max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='route',
            field=models.CharField(blank=True, help_text='Nome da rua', max_length=200, verbose_name='logradouro'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state_code',
            field=models.CharField(blank=True, help_text='Sigla do estado', max_length=5, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='code',
            field=models.SlugField(unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Grupo padrão para novos clientes', verbose_name='padrão'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='price_list_code',
            field=models.CharField(blank=True, help_text='Código da lista de preços no Offerman (convenção: slug=code)', max_length=50, verbose_name='código da lista de preços'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='priority',
            field=models.IntegerField(default=0, help_text='Maior = mais prioridade', verbose_name='prioridade'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='guestman.customer', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='provider',
            field=models.CharField(choices=[('manychat', 'ManyChat'), ('whatsapp', 'WhatsApp Business'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google'), ('apple', 'Apple'), ('telegram', 'Telegram'), ('other', 'Outro')], max_length=20, verbose_name='provedor'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='provider_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Dados extras: page_id, wa_id, ig_scoped_id, tags, etc.', verbose_name='metadados do provedor'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='provider_uid',
            field=models.CharField(help_text='ID único no provedor (ex: Manychat subscriber_id)', max_length=255, verbose_name='ID no provedor'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=255, unique=True)),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'processed event',
                'verbose_name_plural': 'processed events',
                'db_table': 'guestman_processed_event',
                'indexes': [models.Index(fields=['provider', 'processed_at'], name='guestman_pr_provide_8f9f39_idx')],
            },
        ),
    ]
