# Generated by Django 5.2.11 on 2026-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0004_alter_contactpoint_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedevent',
            options={'verbose_name': 'evento processado', 'verbose_name_plural': 'eventos processados'},
        ),
        migrations.AlterField(
            model_name='processedevent',
            name='nonce',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='nonce'),
        ),
        migrations.AlterField(
            model_name='processedevent',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='processado em'),
        ),
        migrations.AlterField(
            model_name='processedevent',
            name='provider',
            field=models.CharField(db_index=True, max_length=50, verbose_name='provedor'),
        ),
    ]
