# Generated by Django 5.2.11 on 2026-02-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0005_alter_processedevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefone'),
        ),
    ]
