# Generated by Django 5.0.3 on 2026-01-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent_q', models.BigIntegerField(default=0, help_text='Total spent in cents')),
                ('average_ticket_q', models.BigIntegerField(default=0, help_text='Average ticket in cents')),
                ('first_order_at', models.DateTimeField(blank=True, null=True)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_order', models.IntegerField(blank=True, null=True)),
                ('average_days_between_orders', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('preferred_weekday', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('preferred_hour', models.IntegerField(blank=True, help_text='Preferred hour (0-23)', null=True)),
                ('favorite_products', models.JSONField(default=list, help_text='List of {sku, name, count, last_ordered}')),
                ('preferred_channel', models.CharField(blank=True, max_length=50)),
                ('channels_used', models.JSONField(default=list, help_text='List of channels used')),
                ('rfm_recency', models.IntegerField(blank=True, help_text='RFM Recency score (1-5)', null=True)),
                ('rfm_frequency', models.IntegerField(blank=True, help_text='RFM Frequency score (1-5)', null=True)),
                ('rfm_monetary', models.IntegerField(blank=True, help_text='RFM Monetary score (1-5)', null=True)),
                ('rfm_segment', models.CharField(blank=True, help_text="RFM segment (e.g., 'champion', 'at_risk', 'new')", max_length=50)),
                ('churn_risk', models.DecimalField(blank=True, decimal_places=2, help_text='0.00 to 1.00', max_digits=3, null=True)),
                ('predicted_ltv_q', models.BigIntegerField(blank=True, help_text='Predicted LTV in cents', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('calculation_version', models.CharField(default='v1', help_text='Calculation algorithm version', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='guestman.customer')),
            ],
            options={
                'verbose_name': 'Customer Insight',
                'verbose_name_plural': 'Customer Insights',
            },
        ),
    ]
