# Generated by Django 5.2.11 on 2026-02-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0005_alter_processedevent_options_and_more'),
        ('guestman_insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinsight',
            options={'verbose_name': 'insight do cliente', 'verbose_name_plural': 'insights dos clientes'},
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='average_days_between_orders',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='média de dias entre pedidos'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='average_ticket_q',
            field=models.BigIntegerField(default=0, help_text='Ticket médio em centavos', verbose_name='ticket médio (centavos)'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='calculated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='calculado em'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='calculation_version',
            field=models.CharField(default='v1', help_text='Versão do algoritmo de cálculo', max_length=20, verbose_name='versão do cálculo'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='channels_used',
            field=models.JSONField(default=list, help_text='Lista de canais utilizados', verbose_name='canais utilizados'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='churn_risk',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.00 a 1.00', max_digits=3, null=True, verbose_name='risco de churn'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='guestman.customer', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='days_since_last_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='dias desde último pedido'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='favorite_products',
            field=models.JSONField(default=list, help_text='Lista de {sku, nome, qtd, ultimo_pedido}', verbose_name='produtos favoritos'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='first_order_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='primeiro pedido em'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='last_order_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último pedido em'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='predicted_ltv_q',
            field=models.BigIntegerField(blank=True, help_text='LTV previsto em centavos', null=True, verbose_name='LTV previsto (centavos)'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='preferred_channel',
            field=models.CharField(blank=True, max_length=50, verbose_name='canal preferido'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='preferred_hour',
            field=models.IntegerField(blank=True, help_text='Hora preferida (0-23)', null=True, verbose_name='hora preferida'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='preferred_weekday',
            field=models.IntegerField(blank=True, help_text='0=Segunda, 6=Domingo', null=True, verbose_name='dia da semana preferido'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='rfm_frequency',
            field=models.IntegerField(blank=True, help_text='Score de frequência RFM (1-5)', null=True, verbose_name='RFM frequência'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='rfm_monetary',
            field=models.IntegerField(blank=True, help_text='Score monetário RFM (1-5)', null=True, verbose_name='RFM monetário'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='rfm_recency',
            field=models.IntegerField(blank=True, help_text='Score de recência RFM (1-5)', null=True, verbose_name='RFM recência'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='rfm_segment',
            field=models.CharField(blank=True, help_text="Segmento RFM (ex: 'campeão', 'em_risco', 'novo')", max_length=50, verbose_name='segmento RFM'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='total_orders',
            field=models.IntegerField(default=0, verbose_name='total de pedidos'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='total_spent_q',
            field=models.BigIntegerField(default=0, help_text='Total gasto em centavos', verbose_name='total gasto (centavos)'),
        ),
    ]
