# Generated by Django 5.0.3 on 2026-01-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('manychat', 'Manychat ID')], max_length=20)),
                ('identifier_value', models.CharField(help_text='Normalized value (phone without formatting, email lowercase)', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary identifier of this type')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When verified (e.g., OTP)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='guestman.customer')),
            ],
            options={
                'verbose_name': 'Identifier',
                'verbose_name_plural': 'Identifiers',
                'indexes': [models.Index(fields=['identifier_type', 'identifier_value'], name='guestman_id_identif_78db49_idx')],
                'unique_together': {('identifier_type', 'identifier_value')},
            },
        ),
    ]
