# Generated by Django 5.2.11 on 2026-02-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0005_alter_processedevent_options_and_more'),
        ('guestman_identifiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeridentifier',
            options={'verbose_name': 'identificador', 'verbose_name_plural': 'identificadores'},
        ),
        migrations.AlterField(
            model_name='customeridentifier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='customeridentifier',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='guestman.customer', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='customeridentifier',
            name='identifier_type',
            field=models.CharField(choices=[('phone', 'Telefone'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('manychat', 'Manychat ID')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='customeridentifier',
            name='identifier_value',
            field=models.CharField(help_text='Valor normalizado (telefone sem formatação, email minúsculo)', max_length=255, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='customeridentifier',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Identificador principal deste tipo', verbose_name='principal'),
        ),
        migrations.AlterField(
            model_name='customeridentifier',
            name='source_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='sistema de origem'),
        ),
        migrations.AlterField(
            model_name='customeridentifier',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Quando foi verificado (ex: OTP)', null=True, verbose_name='verificado em'),
        ),
    ]
